use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# NervesHubWWWWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :nerves_hub_www, NervesHubWWWWeb.Endpoint,
  load_from_system_env: true,
  server: true,
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

config :nerves_hub_device, NervesHubDeviceWeb.Endpoint, server: false

config :nerves_hub_www, NervesHubWWWWeb.AccountController, allow_signups: false

config :logger, level: :debug

config :nerves_hub_www, NervesHubWWW.Mailer,
  adapter: Bamboo.SMTPAdapter,
  tls: :always,
  ssl: false,
  retries: 1

config :rollbax,
  environment: to_string(Mix.env()),
  enabled: true,
  enable_crash_reports: true
